import { NextPageContext } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useSocket } from "../../hooks/useSocket";
import { EVENTS } from "../../socket/events.types";
import { Cookie } from "../../utils/Cookie";
import { STATUS } from "../../utils/GameDataTypes";

export async function getServerSideProps(context: NextPageContext) {
	// get room_id from params
	const { room_id } = context.query;

	const player_id = Cookie.getPlayerID(context.req, context.res);

	return {
		props: {
			room_id,
			player_id,
		},
	};
}

export default function GamePage({
	room_id: roomID,
	player_id,
}: {
	room_id: string;
	player_id: string;
	isPartyLeader: boolean;
}) {
	const [room_id] = useState<string>(roomID);
	const [players, setPlayers] = useState<any[]>([]);
	const [gameStatus, setGameStatus] = useState<string>("in_lobby");
	const [isPartyLeader, setIsPartyLeader] = useState<boolean>(false);

	const { socket } = useSocket();

	console.log(player_id);

	useEffect(() => {
		if (players && players.length > 0) {
			const filteredPartyLeaderPlayerID = players.filter(
				(player) => player.is_party_leader
			)[0].player_id;

			setIsPartyLeader(filteredPartyLeaderPlayerID === player_id);
		}
	}, [players, player_id]);

	useEffect(() => {
		console.log(socket);
		if (socket) {
			console.log("Emitting join_room");

			socket.emit(EVENTS.JOIN_ROOM, {
				room_id: room_id,
			});

			socket.on(EVENTS.ROOM_PLAYERS_UPDATE, (data) => {
				console.log(EVENTS.ROOM_PLAYERS_UPDATE, " received");
				setPlayers(data);
			});

			socket.on(EVENTS.STATUS_CHANGE, (data) => {
				console.log("Status change received");
				setGameStatus(data.status);
			});

			socket.on("disconnect", () => {
				console.log("Disconnected");
				// Tell the server that they have been disconnected
				socket.emit(EVENTS.DISCONNECTED, {
					room_id: room_id,
					player_id,
				});
			});
		}
	}, [socket, room_id, player_id]);

	useEffect(() => {
		if (gameStatus === STATUS.IN_PROGRESS) {
			window.location.href = `/game/${room_id}`;
		}
	}, [gameStatus, room_id]);

	useEffect(() => {
		return () => {
			if (socket) {
				console.log("Leaving room");
				// Tell the server that they have been disconnected
				socket.emit(EVENTS.DISCONNECTED, {
					room_id: room_id,
					player_id,
				});
			}
		};
	}, [player_id, room_id, socket]);

	const setGameToStart = () => {
		if (!socket) return;

		socket.emit(EVENTS.START_GAME, {
			room_id: room_id,
		});
	};

	const setGameToStop = () => {
		if (!socket) return;
		socket.emit(EVENTS.STATUS_CHANGE, {
			room_id: room_id,
			status: STATUS.IN_LOBBY,
		});
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Room ID: {room_id}</h1>

				{players &&
					players.map((player: any) => (
						<div
							key={player.player_id}
							style={{
								color:
									player.player_id === player_id
										? "gold"
										: "",
							}}
						>
							{player.display_name}

							{player.is_party_leader && <span> (Leader)</span>}
						</div>
					))}
			</main>

			{gameStatus === STATUS.IN_PROGRESS && (
				<div>
					<h1>Game is in progress</h1>
				</div>
			)}

			{isPartyLeader && (
				<>
					<button
						onClick={setGameToStart}
						disabled={gameStatus !== STATUS.IN_LOBBY}
					>
						Start Game
					</button>

					<button
						onClick={setGameToStop}
						disabled={gameStatus !== STATUS.IN_PROGRESS}
					>
						Stop Game
					</button>
				</>
			)}
		</div>
	);
}
