import { IconLogout } from "@tabler/icons";
import { motion } from "framer-motion";
import { NextPageContext } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Container from "../../components/Container";
import { useSocket } from "../../hooks/useSocket";
import {
	Action,
	EVENTS,
	Log,
	Player,
	Status,
	TRUTH_OR_DARE_GAME,
} from "../../Types";
import axiosInstance from "../../utils/axiosInstance";
import { Cookie } from "../../utils/Cookie";

export async function getServerSideProps(context: NextPageContext) {
	// get room_id from params
	const { room_id } = context.query;

	let player_id = Cookie.getPlayerID(context.req, context.res);

	if (!player_id) {
		return {
			redirect: {
				destination: "/",
				permanent: false,
			},
		};
	}

	// Find the player using the API
	const playerFromAPI = await axiosInstance.get("/api/player", {
		params: {
			player_id,
		},
	});

	const player = playerFromAPI.data.data;

	if (!player) {
		return {
			redirect: {
				destination: "/",
				permanent: false,
			},
		};
	}

	const rtnPlayer = {
		is_party_leader: player.is_party_leader,
		display_name: player.display_name,
		player_id: player.player_id,
	};

	return {
		props: {
			// Pass the query string to the page
			r: room_id,
			player_id,
			player: rtnPlayer,
		},
	};
}

export default function GamePage({
	r: roomID,
	player_id,
	player,
}: {
	r: string;
	player_id: string;
	player: {
		is_party_leader: boolean;
		player_id: string;
		display_name: string;
	};
}) {
	const [room_id] = useState<string>(roomID);
	const [players, setPlayers] = useState<any[]>([]);

	const [gameStatus, setGameStatus] = useState<string>("in_lobby");

	const [currentPlayer, setCurrentPlayer] = useState<Partial<Player>>({});
	const [action, setAction] = useState<Action>(Action.Waiting_For_Selection);
	const [text, setText] = useState<string>("");

	const { socket } = useSocket();

	useEffect(() => {
		if (socket) {
			console.log("Emitting joined truth or dare game");

			socket.emit(TRUTH_OR_DARE_GAME.JOINED, {
				room_id: room_id,
				player_id: player_id,
			});

			socket.on(EVENTS.PLAYERS_UPDATE, (data) => {
				console.log(EVENTS.PLAYERS_UPDATE, " received");
				setPlayers(data);
			});

			socket.on(EVENTS.GAME_UPDATE, (data) => {
				console.log("Status change received");
				setGameStatus(data.status);
			});

			socket.on(
				TRUTH_OR_DARE_GAME.CONTINUE,
				(log: Log, player: Player) => {
					console.log("Continue game received");
					console.log(log, player);
					setCurrentPlayer(player);
					setText("");
					setAction(log.action as Action);
				}
			);

			socket.on(
				TRUTH_OR_DARE_GAME.INCOMING_DATA,
				(log: Log, player: Player) => {
					console.log("New data received");
					console.log(log, player);

					setText(log.data);
					setCurrentPlayer(player ?? {});
					setAction(
						(log.action as Action) ??
							(Action.Waiting_For_Selection as Action)
					);
				}
			);

			socket.on("disconnect", () => {
				console.log("Disconnected");
				// Tell the server that they have been disconnected
				socket.emit(EVENTS.DISCONNECTED, {
					room_id: room_id,
					player_id,
				});
			});
		}
	}, [socket, room_id, player_id]);

	const inLobbyGame = () => {
		if (!socket) return;
		socket.emit(EVENTS.GAME_UPDATE, {
			room_id: room_id,
			status: Status.In_Lobby,
		});
	};

	const selectTruth = () => {
		console.log("Selecting truth");
		console.log(!!socket);
		if (!socket) return;
		console.log("Emitting to server to select truth");
		socket.emit(TRUTH_OR_DARE_GAME.SELECT_TRUTH, {
			room_id: room_id,
			player_id: player_id,
		});
	};

	const selectDare = () => {
		if (!socket) return;
		socket.emit(TRUTH_OR_DARE_GAME.SELECT_DARE, {
			room_id: room_id,
			player_id: player_id,
		});
	};

	const handleContinue = () => {
		if (!socket) return;
		socket.emit(TRUTH_OR_DARE_GAME.CONTINUE, {
			room_id: room_id,
		});
	};

	const handleLeaveGame = () => {
		if (!socket) return;
		socket.emit(TRUTH_OR_DARE_GAME.LEAVE_GAME, {
			room_id: room_id,
			player_id: player_id,
		});

		window.location.href = "/";
	};

	return (
		<>
			<Container>
				<Head>
					<title>Game</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<div className="w-full h-[80%] flex items-center justify-center">
					{/* Main items */}
					<div>
						{/* <main>
				<p>Room ID: {room_id}</p>
				<p>Player ID: {player_id}</p>
				<p>Player Name: {player.display_name}</p>
			</main> */}

						<p className="font-bold text-sm text-center my-10">
							<span className="bg-black text-white rounded-lg py-1 px-2">
								Room Code: {room_id}
							</span>
						</p>

						{/* Current Player Name */}
						<main className="w-full flex items-center justify-center my-10">
							<div className="rnd bdr w-fit px-10 py-5">
								<h1 className="font-Playfair font-black text-5xl text-center">
									{currentPlayer.display_name}
								</h1>
							</div>
						</main>

						{/* If it is the current player and the action is to wait for a selection, Show the selection truth or dare buttons */}
						{currentPlayer.player_id === player_id &&
							action === Action.Waiting_For_Selection && (
								<>
									<p className="text-center">Select One</p>

									<div className="flex flex-wrap items-center justify-center gap-5 my-20">
										<motion.button
											whileHover={{ scale: 1.1, y: -10 }}
											whileTap={{ scale: 0.9 }}
											className="btn-huge w-[200px] aspect-square"
											onClick={selectTruth}
										>
											Truth
										</motion.button>

										<motion.button
											whileHover={{ scale: 1.1, y: -10 }}
											whileTap={{ scale: 0.9 }}
											className="btn-huge w-[200px] aspect-square"
											onClick={selectDare}
										>
											Dare
										</motion.button>
									</div>
								</>
							)}

						{/* Show this below if the current player is not the player and that the action is waiting for selection */}
						{currentPlayer.player_id !== player_id &&
							action === Action.Waiting_For_Selection && (
								<p className="text-center">
									Waiting for {currentPlayer.display_name} to
									select
								</p>
							)}

						{/* The truth/dare text */}
						{action !== Action.Waiting_For_Selection && (
							<>
								<div className="rnd bdr w-fit px-10 py-5 space-y-4">
									<h2 className="text-center text-3xl font-semibold">
										{text}
									</h2>
								</div>
							</>
						)}

						{/* If it is the current player and they're not waiting for selection */}
						{currentPlayer.player_id === player_id &&
							action !== Action.Waiting_For_Selection && (
								<div>
									<motion.button
										whileHover={{
											scale: 1.01,
										}}
										whileTap={{
											scale: 0.9,
										}}
										className="btn my-10 t bg-green-400 text-black/50"
										onClick={handleContinue}
									>
										Continue
									</motion.button>
								</div>
							)}

						{/* Show Force Continue button for party leader */}
						{player.is_party_leader &&
							currentPlayer.player_id !== player.player_id && (
								<div>
									<motion.button
										whileHover={{ scale: 1.05 }}
										whileTap={{ scale: 0.9 }}
										className="btn my-10 bg-black/10 border-none"
										onClick={handleContinue}
									>
										Force Continue
									</motion.button>
								</div>
							)}
					</div>
				</div>
			</Container>

			<div className="fixed bottom-0 w-full">
				<div className="flex justify-between items-center bg-black/10 px-5 py-2">
					<div className="flex flex-col gap-3">
						{/* <p className="font-bold text-sm">
							Room Code:{" "}
							<span className="bg-black text-white rounded-lg py-1 px-2">
								{room_id}
							</span>
						</p> */}

						<p className="text-sm font-bold">
							<span className="font-black bg-black font-Playfair text-white rounded-lg py-1 px-2">
								{player.display_name}
							</span>
						</p>
					</div>

					<div className="">
						<motion.button
							whileHover={{ scale: 1.05 }}
							whileTap={{ scale: 0.9 }}
							className="btn my-1 bg-red-500 text-white border-none flex items-center gap-2 text-sm"
							onClick={handleLeaveGame}
						>
							<IconLogout size={16} />
							Leave
						</motion.button>
					</div>
				</div>
			</div>
		</>
	);
}
