import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
	const [roomIDInput, setRoomIDInput] = useState<string>("");
	const [displayName, setDisplayName] = useState<string>("");

	const joinGame = () => {
		if (roomIDInput.trim()) {
			// Redirect to the join page
			window.location.href = `/join/${roomIDInput}?display_name=${displayName}`;
		}
	};

	const createNewRoom = () => {
		// Redirect to the create page
		window.location.href = "/create?display_name=" + displayName;
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<input
					type={"text"}
					placeholder="Room ID"
					value={roomIDInput}
					onChange={(e) => setRoomIDInput(e.target.value)}
				/>

				<input
					type={"text"}
					placeholder="Display Name"
					value={displayName}
					onChange={(e) => setDisplayName(e.target.value)}
				/>

				<button disabled={!!roomIDInput} onClick={createNewRoom}>
					Create Room
				</button>
				<button onClick={joinGame}>Join Room</button>
				{/* <button onClick={giveTruth}>Truth</button> */}
				{/* <button onClick={giveDare}>Dare</button> */}
			</main>
		</div>
	);
}
